### ISSUE TITLE
Executing instructions in a declaritive manner 

### ISSUE THREAD

**Issue by Akilan1999** [DiscoRiver/massh#7]
# Amazing work on this project ! 

## Addressing problem 
If a user wants to execute large set of shell commands. It would annoying to always create a Go program every single time and setting the instructions in an array.  

## Solution 
Based on the inspiration of Ansibles. We can set a simple yaml or json file which consists of an array of strings of shell commands to be executed. 

## Reason behind this
I am working a p2p network for executing custom scripts. Currently I am using Ansibles as a plugin system. But it's extremely cluttered and requires external dependencies. If I can implement the following issue. I can use your project as a plugin system to my project. 
Project link: https://github.com/Akilan1999/p2p-rendering-computation

**Comment by DiscoRiver** [comment]
Thanks for the feedback!

Just so I can fully understand your suggestion, is your requirement to be able to feed multiple shell commands into a single **Job**, rather than needing to build a separate **massh.Job** for each of your commands?

**Comment by Akilan1999** [comment]
I my case it's either executing each shell command one by one or uploading a bash script to host and executing it from there. 
I am going guess each shell command is going to be a separate maash.Job .

**Comment by DiscoRiver** [comment]
Thanks! Based on what I think you're after, I have one point;

- Having Massh read from a file to grab command isn't really within the scope of the package. I would expect that logic to be part of your project, and you would feed this into Massh based on your requirements. 

However, the change I can make to better facilitate the behaviour you're looking for is to allow **massh.Config** to accept a slice of **Job**. For example, it could alow you to do something like this;

```
var myCommands []string
... // Some code to get your commands/arguments from a file, into myCommands

config := massh.Config{}
... // Set up other parts of config

jobs := []massh.Job{}

for i := range myCommands {
    tmpJob := massh.Job{
        Command: myCommands[i]
    }

    jobs = append(jobs, tmpJob)
}

config.Jobs = &jobs

res, err := config.Run()
if err != nil {
    panic(err)
}

// Do something with the results
```

In this case, for compatibility, I would be adding `Jobs` to `Config`, which will accept a slice of Jobs to be performed. 

Would that fit your requirements?

**Comment by Akilan1999** [comment]
Yes !
This would do !

**Comment by DiscoRiver** [comment]
Excellent, I'll work on that! Thanks again.

**Comment by Akilan1999** [comment]
This is a really useful package ! 
Amazing work on building it. Hopefully more ppl use it.

**Comment by DiscoRiver** [comment]
@Akilan1999 Do you want to have a look at my changes and ensure they align with your requirements?

The new `config.JobStack` value should be what you're looking for. Some changes need to be made if streaming, as the concurrency model needs to account for the fact that we're running multiple tasks per host. Have a look at the example in `_examples` and let me know if you have questions, or if you run into issues.

**Comment by Akilan1999** [comment]
@DiscoRiver  Sure I will have to look at today !
